######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 24 16:01:42 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = libclbio \
          libclbmath